const cfg=window.COUPONHUB_CONFIG;const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);let coupons=[],selected=null,signup=false;
const $=s=>document.querySelector(s);
async function load(){let {data,error}=await sb.from('coupons').select('*').order('created_at',{ascending:false});if(error){console.error(error);return}coupons=data||[];render()}
function render(){let q=$('#search').value.toLowerCase();$('#products').innerHTML=coupons.filter(c=>(c.title+c.brand+c.category).toLowerCase().includes(q)).map(c=>`<article class="card"><div class="emoji">🏷️</div><div class="brand">${c.brand} • ${c.category}</div><h3>${c.title}</h3><p>${c.description||''}</p><div class="price">₹${c.selling_price.toLocaleString('en-IN')} <span class="old">₹${c.original_price.toLocaleString('en-IN')}</span></div><button class="buy" onclick="buy('${c.id}')">Buy Coupon</button></article>`).join('')||'<p>No coupons found.</p>'}
async function buy(id){const {data:{user}}=await sb.auth.getUser();if(!user){showAuth();return}selected=coupons.find(c=>c.id===id);$('#payText').textContent=`${selected.title} — ₹${selected.selling_price}`;$('#pay').classList.add('show')}
async function startPay(){let {data:{session}}=await sb.auth.getSession();if(!session)return;let r=await fetch('/api/payment/create',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({couponId:selected.id})});let d=await r.json();if(!r.ok)return alert(d.error);if(!window.Razorpay){let s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';document.head.appendChild(s);await new Promise(x=>s.onload=x)}let rz=new Razorpay({key:d.keyId,amount:d.amount,currency:d.currency,name:'CouponHub',description:selected.title,order_id:d.orderId,handler:async resp=>{let vr=await fetch('/api/payment/verify',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({...resp,dbOrderId:d.dbOrderId})});let vd=await vr.json();if(vd.ok){hidePay();alert('Payment successful! Your coupon code: '+vd.code);loadOrders()}else alert(vd.error)}});rz.open()}
async function loadOrders(){let {data:{user}}=await sb.auth.getUser();if(!user){$('#ordersList').textContent='Login to view your orders.';return}let {data}=await sb.from('orders').select('*,coupons(title,brand)').order('created_at',{ascending:false});$('#ordersList').innerHTML=(data||[]).map(o=>`<div class="order"><b>${o.coupons?.title||'Coupon'}</b><br>₹${o.amount} • ${o.status}<br>${o.coupon_code?`Code: <span class="code">${o.coupon_code}</span>`:''}</div>`).join('')||'No orders yet.'}
function showAuth(){signup=false;$('#authTitle').textContent='Login';$('#authAction').textContent='Login';$('#switch').textContent='Create account';$('#auth').classList.add('show')}function hideAuth(){$('#auth').classList.remove('show')}function hidePay(){$('#pay').classList.remove('show')}
$('#loginBtn').onclick=showAuth;$('#switch').onclick=e=>{e.preventDefault();signup=!signup;$('#authTitle').textContent=signup?'Create account':'Login';$('#authAction').textContent=signup?'Create account':'Login';$('#switch').textContent=signup?'Already have an account? Login':'Create account'};
$('#authAction').onclick=async()=>{let email=$('#email').value,password=$('#password').value;if(signup){let r=await sb.auth.signUp({email,password});if(r.error)return $('#authMsg').textContent=r.error.message;$('#authMsg').textContent='Check your email to confirm your account.'}else{let r=await sb.auth.signInWithPassword({email,password});if(r.error)return $('#authMsg').textContent=r.error.message;hideAuth();loadOrders()}};
$('#payAction').onclick=startPay;$('#search').oninput=render;
sb.channel('public-live').on('postgres_changes',{event:'*',schema:'public',table:'coupons'},()=>load()).on('postgres_changes',{event:'*',schema:'public',table:'orders'},()=>loadOrders()).subscribe();
sb.auth.onAuthStateChange(()=>loadOrders());load();loadOrders();